filter:
    excluded_paths: [features/*, tests/*]

checks:
    php: true

build:
    image: default-jammy
    environment:
        php: 8.2.15
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
