language: php
#sudo: required
#services:
#  - docker
env:
  COMPOSE_VERSION: 1.11.1
php:
  - 5.6
  - 7.0
  - 7.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpspec run --format=dot
#  - docker-compose up -d
#  - vendor/bin/behat -f progress
#  - docker-compose stop

