language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_install:
    - curl -L https://github.com/docker/compose/releases/download/1.11.1/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-dist -o

script:
    - vendor/bin/phpspec run --format=dot
    - docker-compose up -d
    - vendor/bin/behat -f progress
    - docker-compose stop
