<?php

/**
 * This file is part of web-stack
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Slick\WebStack\Domain\Security;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

/**
 * SecurityAuthenticatorInterface
 *
 * @package Slick\WebStack\Domain\Security
 */
interface SecurityAuthenticatorInterface
{

    /**
     * Checks if the security process is enabled.
     *
     * @return bool True if the functionality is enabled, false otherwise.
     */
    public function enabled(): bool;

    public function user(): ?UserInterface;

    /**
     * Processes security profile for the given server request and optionally returns a response.
     *
     * @param ServerRequestInterface $request The server request to process.
     * @return ResponseInterface|null Returns the response generated by processing the request,
     *                                or null if no response is generated.
     */
    public function process(ServerRequestInterface $request): ?ResponseInterface;

    /**
     * Get the authentication errors.
     *
     * @return array<string> An array of authentication errors.
     */
    public function authenticationErrors(): array;

    /**
     * Logs out the current user.
     *
     * @return void
     */
    public function logout(): void;

    /**
     * Logs in the user using the provided UserInterface.
     *
     * @param UserInterface $user The user to log in.
     * @return void
     */
    public function login(UserInterface $user): void;
}
