routes:
  home:
    allows: [POST, GET]
    path: /
    defaults:
      action: home
  catchall:
    allows: [POST, GET]
    path: "{/controller,action}"
    wildcard: args
defaults:
  namespace: Features\App\Controller
  action: index
  controller: pages