day-off-request:
  path: /request/days-off/{userId}
  allows: [POST, GET]
  defaults:
    controller: daysOff
    action: request
correction-request:
  path: /correction/for/{userId}
  allows: [POST, GET]
  defaults:
    controller: correction
    action: handle
flights-request:
  path: /request/flight/{userId}
  allows: [GET, POST]
  defaults:
    controller: flights
    action: request
profile:
  path: /profile
  allows: [POST, GET]
  defaults:
    namespace: UsersPlugin\Controller
    controller: profile
    action: edit


about-page:
  path: /about
  method: GET
  defaults:
    controller: pages
    action: about
pretension-show:
  path: /pretensions/show
  wildcard: args
  allows: [GET, POST]
  auth:
    - Administrator
    - PGT Manager
  defaults:
    controller: pretensions
    action: show

pretensions-current-status:
  path: /pretensions/currentStatus
  wildcard: args
  allows: [GET, POST]
  auth:
    - Administrator
    - PGT Manager
  defaults:
    controller: pretensions
    action: currentStatus

pretensions-list:
  path: /pretensions{/action}
  wildcard: args
  allows: [GET, POST]
  auth:
    - Administrator
    - PGT Manager
  defaults:
    controller: pretensions-controller

dashboard:
  path: /dashboard
  method: GET
  defaults:
    controller: pretensions-controller
  auth:
    - Administrator
    - PGT Manager

