<?php

/**
 * This file is part of web-stack
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Slick\WebStack\Domain\Security\Http;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

/**
 * SecurityProfileInterface
 *
 * @package Slick\WebStack\Domain\Security\Http
 */
interface SecurityProfileInterface
{
    /**
     * Checks if the given request matches the defined match expression.
     *
     * @param ServerRequestInterface $request The server request to match against.
     * @return bool Returns true if the request matches the match expression, false otherwise.
     */
    public function match(ServerRequestInterface $request): bool;

    /**
     * Processes security profile for the given server request and optionally returns a response.
     *
     * @param ServerRequestInterface $request The server request to process.
     * @return ResponseInterface|null Returns the response generated by processing the request,
     *                                or null if no response is generated.
     */
    public function process(ServerRequestInterface $request): ?ResponseInterface;

    /**
     * Returns an array containing authentication errors.
     *
     * @return array<string> Returns an array of authentication errors.
     */
    public function authenticationErrors(): array;
}
